// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHXKB7cvzLSSYv5Nwjj_IJmFvsgFbRt-M',
    appId: '1:716649129108:web:f88c76c2723f7e6d170081',
    messagingSenderId: '716649129108',
    projectId: 'emsiapp-d9641',
    authDomain: 'emsiapp-d9641.firebaseapp.com',
    storageBucket: 'emsiapp-d9641.firebasestorage.app',
    measurementId: 'G-QTNGT02DN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswjU_uiNGtc5Jxg0mQ7fubE0kcqiACgk',
    appId: '1:716649129108:android:c57ad7b6553a47dc170081',
    messagingSenderId: '716649129108',
    projectId: 'emsiapp-d9641',
    storageBucket: 'emsiapp-d9641.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHXKB7cvzLSSYv5Nwjj_IJmFvsgFbRt-M',
    appId: '1:716649129108:web:919942b474f1868f170081',
    messagingSenderId: '716649129108',
    projectId: 'emsiapp-d9641',
    authDomain: 'emsiapp-d9641.firebaseapp.com',
    storageBucket: 'emsiapp-d9641.firebasestorage.app',
    measurementId: 'G-K5BVE5E2ZW',
  );
}
